mysql:
    host: localhost
    user: root
    database: DeribitOrderBook

orderBookScrapper:
    depth: 10
    test_net: False
    currency: BTC
    enable_traceback: False
    enable_database_record: True
    clean_database: True
    hearth_beat_time: 60
    group_in_limited_order_book: none
    raise_error_at_synthetic: False
    logger_level: INFO

    select_all_order_book: True


